travis:
  secure:
    BINSTAR_TOKEN: W1wKdKBHGeF9knapdxpNXFqUPh6vwn6XYa4PcrgdFBFfjfYpr3UqCXPQUpLes4X2P0pND/XAp6AQkSSiBVfswBWTe/k4E6rz0xSKQ8EjHYk6USfMgE9/zboWL0nilJ/BpC1Erbr/OIxQXjRRaUMehnp8z2w/EfDQ06708dBi7INYjX1EEt27LfI7kDXt32w/hS09VbMNRX52RoNu93fjWJunS6tYaDpA9FxpEoteR4e8ScXOpOzvIrVRE/PEtgw44dBEq899XH0j6Pu2E+YgHOQ9HpyK3vQF9/EJb0u7IwIlH23umknk6BBW/r9PUM3Ucknfy5dUVcojKJ2hJMCkUegiTarmGXdWFhl1i5I86tzRMp83C659f4VPmVWzdstP/8VXV5hX+KgCl+3YOmszkvcywUnRiYlXeklsvZ7riycDFCrUPzS8m9dzdr3MdvQohGUmlcFm0UlYOgL1m9ekLkN1/9iwLZX4BgD4UoLpyi6206e2FSyJ1fR/bZkV7lZubpqeIK78jZ0ucHO+auYl0c+3jdmc0LKhol62Gj2W7cM5DNtdErsF6/zD63G2vPASjpSZJdn0Op+aifBW2Lvw16GsVLNC9E8HR/XAwzFkW5jfI1mJZ5QFEBI/fHae/WE5xgK7jLzQCy0HMllwK4my46gBkp/xcLDn8ETjzcdqET8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
